### ISSUE TITLE
[BUG] Classifier training much slower in 1.8.0 on aarch64

### ISSUE THREAD

**Issue by pedrom34** [paperless-ngx/paperless-ngx#1364]
### Description

Version 1.7.1 is working fine. When I update to 1.8.0 everything is working fine for 5 minutes and then htop shows me that "python3 manage.py qcluster" is using more than 100% of cpu, the whole system becomes unreachable. I have to manually reboot.

### Steps to reproduce

- Deploy paperless 1.8.0
- Wait 5 minutes for crash

Here's my docker-compose file:
```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:6.0
    restart: unless-stopped
    volumes:
      - /mnt/dietpi_userdata/portainer/paperless/redis:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - /mnt/dietpi_userdata/portainer/paperless/pgdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:1.8.0
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/dietpi_userdata/portainer/paperless/p-data:/usr/src/paperless/data
      - /mnt/docs/Paperless/media:/usr/src/paperless/media
      - /mnt/docs/Paperless/export:/usr/src/paperless/export
      - /mnt/docs/Paperless/00.consume:/usr/src/paperless/consume

    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_OCR_LANGUAGE: fra
      PAPERLESS_SECRET_KEY: secret
      PAPERLESS_TIME_ZONE: Europe/Paris
      PAPERLESS_CONSUMER_POLLING: 900
      PAPERLESS_FILENAME_FORMAT: "{correspondent}/{document_type}/{created_year}{created_month}{created_day}-{title}"
      PAPERLESS_ALLOWED_HOSTS: "localhost,192.168.0.11:8000,https://paperless.domain.tld"
      PAPERLESS_URL: "https://paperless.domain.tld"

volumes:
  data:
  media:
  pgdata:
  redisdata:
```

### Webserver logs

```bash
Latest lines before crash : 
[2022-08-05 16:04:27,710] [INFO] [paperless.migrations] Conversion to WebP completed, replaced 0000098.png with 0000098.webp
[2022-08-05 16:04:27,991] [INFO] [paperless.migrations] Conversion to WebP completed, replaced 0000606.png with 0000606.webp
[2022-08-05 16:04:28,020] [INFO] [paperless.migrations] Conversion completed in 108.198s
[2022-08-05 16:04:52,979] [INFO] [paperless.management.consumer] Polling directory for changes: /usr/src/paperless/consume
[2022-08-05 16:05:25,902] [INFO] [paperless.classifier] Classifier version updated, will re-train
[2022-08-05 16:05:26,009] [DEBUG] [paperless.classifier] Gathering data from database...
[2022-08-05 16:05:50,886] [DEBUG] [paperless.classifier] 913 documents, 27 tag(s), 59 correspondent(s), 29 document type(s). 0 storage path(es)
[2022-08-05 16:05:56,180] [DEBUG] [paperless.classifier] Vectorizing data...
[2022-08-05 16:06:18,812] [DEBUG] [paperless.classifier] Training tags classifier...
```

### Paperless-ngx version

1.8.0

### Host OS

 Device model : ROCK64 (aarch64), running debian (dietpi)

### Installation method

Docker - official image

### Other

I deploy using portainer

**Comment by stumpylog** [comment]
From the webserver logs, it's attempting to retrain the classifier model used for automatic matching.  scikit-learn updated to 1.1.1, which is the only obvious change that may affect this.

On 1.7.1, does training the classifier (with the same documents) work without issue?

**Comment by stumpylog** [comment]
Also, how much memory is your ROCK64?  Looks like they come in a few options

**Comment by pedrom34** [comment]
> On 1.7.1, does training the classifier (with the same documents) work without issue?
How can I test that?

> Also, how much memory is your ROCK64? Looks like they come in a few options
Mine has 4G. With paperless running, I'm at something like 50% used.

**Comment by pedrom34** [comment]
I just issued "document_create_classifier" on my working 1.7.1 instance. No issue at all.

Is this what you meant by training the classifier?

**Comment by stumpylog** [comment]
Yes, that should retrain the classifier.  It doesn't seem likely to be a memory issue, my own instance only raises the memory usage by a few hundred megabytes when training.

Nothing besides the version update changed with the classification. How long did it take on 1.7.1?  And how long have you tried waiting for it on 1.8?

**Comment by pedrom34** [comment]
It takes under a minute to train on 1.7.1.
On 1.8, the longest I waited before rebooting the system was something like 4 to 5 hours.

Before opening this issue I tried to update from a fresh install of 1.7.1 in which I imported a working export. 
Is there something else I could try?

**Comment by stumpylog** [comment]
Wow.  That's quite a change.  I'm guessing there's a library missing or not linked against for either numpy or scipy, so it's falling back to some sort of pure Python.  I don't have an Arm device of any sort to check against, so if you can do the following for 1.7.1 and 1.8 and provide the output, that would be awesome:

1. Get a shell into the container: `docker exec -it webserver /bin/bash` (webserver or something like that)
2. Get a Python session: `python3`
3. `import numpy`
4. `import scipy`
5. `numpy.show_config()`
6. `scipy.show_config()`
7. Exit Python: `exit()`
8. Exit container shell: `exit`

**Comment by pedrom34** [comment]
OK, I will do in the next week, no problem. Thanks a lot 🙏

Shall I do it on a fresh empty install of 1.8 or on my 1.7.1 that I update?

**Comment by pedrom34** [comment]
Ok, here we go.

## Here's numpy.show_config()
### In 1.7.1
>numpy.show_config()
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    found = 
    not found = ASIMDHP,ASIMDDP
  
### In 1.8.0
>numpy.show_config()
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    found = 
    not found = ASIMDHP,ASIMDDP,ASIMDFHM

## And here's scipy.show_config()
### in 1.7.1
> scipy.show_config()
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']

### In 1.8.0:
> scipy.show_config()
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']`

**Comment by stumpylog** [comment]
Well, I do see one difference there in numpy, relating to some certain CPU instructions.  Could you try `pip install numpy==1.22.3` and run the `document_create_classifier` command again?

**Comment by pedrom34** [comment]
Done!
Classifier took 6 minutes to run. For the moment everything works 👍 

But I'm a bit worried if I'm the only one running in this issue...

**Comment by stumpylog** [comment]
Well, that's a work around at least, but it won't last through a restart of the container, and then the scheduled task will hang the system again.

@qcasey Do you have an install running aarch64 on a Raspberry Pi?  If yes, could you toss some documents in there and see if the classifier training takes forever?  And/or if `np.show_config()` is also missing ASIMDFHM?

**Comment by pedrom34** [comment]
I might have a spare raspberry 3 that I can  use if @qcasey doesn't have one. But I cannot run the tests before the weekend after the next one...

**Comment by qcasey** [comment]
Nothing unusual here...

```bash
$ uname -m
aarch64

$ docker-compose exec webserver /bin/bash
$ time document_create_classifier

real	0m4.041s
user	0m3.576s
sys	0m0.453s
```


<details>
<summary>docker-compose logs -f</summary>


```
Attaching to paperless-ngx_webserver_1, paperless-ngx_db_1, paperless-ngx_broker_1
db_1         | 
db_1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1         | 
db_1         | 2022-08-08 21:23:33.781 UTC [1] LOG:  starting PostgreSQL 13.7 (Debian 13.7-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db_1         | 2022-08-08 21:23:33.782 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1         | 2022-08-08 21:23:33.782 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1         | 2022-08-08 21:23:33.840 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1         | 2022-08-08 21:23:33.862 UTC [26] LOG:  database system was shut down at 2022-08-08 21:23:19 UTC
db_1         | 2022-08-08 21:23:33.881 UTC [1] LOG:  database system is ready to accept connections
db_1         | 2022-08-08 21:23:37.435 UTC [34] ERROR:  relation "documents_document" does not exist at character 583
db_1         | 2022-08-08 21:23:37.435 UTC [34] STATEMENT:  SELECT "documents_document"."id", "documents_document"."correspondent_id", "documents_document"."storage_path_id", "documents_document"."title", "documents_document"."document_type_id", "documents_document"."content", "documents_document"."mime_type", "documents_document"."checksum", "documents_document"."archive_checksum", "documents_document"."created", "documents_document"."modified", "documents_document"."storage_type", "documents_document"."added", "documents_document"."filename", "documents_document"."archive_filename", "documents_document"."archive_serial_number" FROM "documents_document" WHERE "documents_document"."storage_type" = 'gpg' ORDER BY "documents_document"."created" DESC LIMIT 1
broker_1     | 1:C 08 Aug 2022 21:23:33.442 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
broker_1     | 1:C 08 Aug 2022 21:23:33.442 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=1, just started
broker_1     | 1:C 08 Aug 2022 21:23:33.442 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
broker_1     | 1:M 08 Aug 2022 21:23:33.446 * Running mode=standalone, port=6379.
broker_1     | 1:M 08 Aug 2022 21:23:33.446 # Server initialized
broker_1     | 1:M 08 Aug 2022 21:23:33.446 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
broker_1     | 1:M 08 Aug 2022 21:23:33.451 * Loading RDB produced by version 6.0.16
broker_1     | 1:M 08 Aug 2022 21:23:33.452 * RDB age 14 seconds
broker_1     | 1:M 08 Aug 2022 21:23:33.452 * RDB memory usage when created 0.80 Mb
broker_1     | 1:M 08 Aug 2022 21:23:33.452 * DB loaded from disk: 0.001 seconds
broker_1     | 1:M 08 Aug 2022 21:23:33.452 * Ready to accept connections
webserver_1  | Paperless-ngx docker container starting...
webserver_1  | Creating directory /tmp/paperless
webserver_1  | Adjusting permissions of paperless files. This may take a while.
webserver_1  | Waiting for PostgreSQL to start...
webserver_1  | Waiting for Redis: redis://broker:6379
webserver_1  | Connected to Redis broker: redis://broker:6379
webserver_1  | Apply database migrations...
webserver_1  | Operations to perform:
webserver_1  |   Apply all migrations: admin, auth, authtoken, contenttypes, django_q, documents, paperless_mail, sessions
webserver_1  | Running migrations:
webserver_1  |   Applying contenttypes.0001_initial... OK
webserver_1  |   Applying auth.0001_initial... OK
webserver_1  |   Applying admin.0001_initial... OK
webserver_1  |   Applying admin.0002_logentry_remove_auto_add... OK
webserver_1  |   Applying admin.0003_logentry_add_action_flag_choices... OK
webserver_1  |   Applying contenttypes.0002_remove_content_type_name... OK
webserver_1  |   Applying auth.0002_alter_permission_name_max_length... OK
webserver_1  |   Applying auth.0003_alter_user_email_max_length... OK
webserver_1  |   Applying auth.0004_alter_user_username_opts... OK
webserver_1  |   Applying auth.0005_alter_user_last_login_null... OK
webserver_1  |   Applying auth.0006_require_contenttypes_0002... OK
webserver_1  |   Applying auth.0007_alter_validators_add_error_messages... OK
webserver_1  |   Applying auth.0008_alter_user_username_max_length... OK
webserver_1  |   Applying auth.0009_alter_user_last_name_max_length... OK
webserver_1  |   Applying auth.0010_alter_group_name_max_length... OK
webserver_1  |   Applying auth.0011_update_proxy_permissions... OK
webserver_1  |   Applying auth.0012_alter_user_first_name_max_length... OK
webserver_1  |   Applying authtoken.0001_initial... OK
webserver_1  |   Applying authtoken.0002_auto_20160226_1747... OK
webserver_1  |   Applying authtoken.0003_tokenproxy... OK
webserver_1  |   Applying django_q.0001_initial... OK
webserver_1  |   Applying django_q.0002_auto_20150630_1624... OK
webserver_1  |   Applying django_q.0003_auto_20150708_1326... OK
webserver_1  |   Applying django_q.0004_auto_20150710_1043... OK
webserver_1  |   Applying django_q.0005_auto_20150718_1506... OK
webserver_1  |   Applying django_q.0006_auto_20150805_1817... OK
webserver_1  |   Applying django_q.0007_ormq... OK
webserver_1  |   Applying django_q.0008_auto_20160224_1026... OK
webserver_1  |   Applying django_q.0009_auto_20171009_0915... OK
webserver_1  |   Applying django_q.0010_auto_20200610_0856... OK
webserver_1  |   Applying django_q.0011_auto_20200628_1055... OK
webserver_1  |   Applying django_q.0012_auto_20200702_1608... OK
webserver_1  |   Applying django_q.0013_task_attempt_count... OK
webserver_1  |   Applying django_q.0014_schedule_cluster... OK
webserver_1  |   Applying documents.0001_initial... OK
webserver_1  |   Applying documents.0002_auto_20151226_1316... OK
webserver_1  |   Applying documents.0003_sender... OK
webserver_1  |   Applying documents.0004_auto_20160114_1844... OK
webserver_1  |   Applying documents.0005_auto_20160123_0313... OK
webserver_1  |   Applying documents.0006_auto_20160123_0430... OK
webserver_1  |   Applying documents.0007_auto_20160126_2114... OK
webserver_1  |   Applying documents.0008_document_file_type... OK
webserver_1  |   Applying documents.0009_auto_20160214_0040... OK
webserver_1  |   Applying documents.0010_log... OK
webserver_1  |   Applying documents.0011_auto_20160303_1929... OK
webserver_1  |   Applying documents.0012_auto_20160305_0040... OK
webserver_1  |   Applying documents.0013_auto_20160325_2111... OK
webserver_1  |   Applying documents.0014_document_checksum... OK
webserver_1  |   Applying documents.0015_add_insensitive_to_match... OK
webserver_1  |   Applying documents.0016_auto_20170325_1558... OK
webserver_1  |   Applying documents.0017_auto_20170512_0507... OK
webserver_1  |   Applying documents.0018_auto_20170715_1712... OK
webserver_1  |   Applying documents.0019_add_consumer_user... OK
webserver_1  |   Applying documents.0020_document_added... OK
webserver_1  |   Applying documents.0021_document_storage_type... OK
webserver_1  |   Applying documents.0022_auto_20181007_1420... OK
webserver_1  |   Applying documents.0023_document_current_filename... OK
webserver_1  |   Applying documents.1000_update_paperless_all... OK
webserver_1  |   Applying documents.1001_auto_20201109_1636... OK
webserver_1  |   Applying documents.1002_auto_20201111_1105... OK
webserver_1  |   Applying documents.1003_mime_types... OK
webserver_1  |   Applying documents.1004_sanity_check_schedule... OK
webserver_1  |   Applying documents.1005_checksums... OK
webserver_1  |   Applying documents.1006_auto_20201208_2209... OK
webserver_1  |   Applying documents.1007_savedview_savedviewfilterrule... OK
webserver_1  |   Applying documents.1008_auto_20201216_1736... OK
webserver_1  |   Applying documents.1009_auto_20201216_2005... OK
webserver_1  |   Applying documents.1010_auto_20210101_2159... OK
webserver_1  |   Applying documents.1011_auto_20210101_2340... OK
webserver_1  |   Applying documents.1012_fix_archive_files... OK
webserver_1  |   Applying documents.1013_migrate_tag_colour... OK
webserver_1  |   Applying documents.1014_auto_20210228_1614... OK
webserver_1  |   Applying documents.1015_remove_null_characters... OK
webserver_1  |   Applying documents.1016_auto_20210317_1351... OK
webserver_1  |   Applying documents.1017_alter_savedviewfilterrule_rule_type... OK
webserver_1  |   Applying documents.1018_alter_savedviewfilterrule_value... OK
webserver_1  |   Applying documents.1019_uisettings... OK
webserver_1  |   Applying documents.1019_storagepath_document_storage_path... OK
webserver_1  |   Applying documents.1020_merge_20220518_1839... OK
webserver_1  |   Applying documents.1021_webp_thumbnail_conversion... OK
webserver_1  |   Applying documents.1022_paperlesstask... OK
webserver_1  |   Applying paperless_mail.0001_initial... OK
webserver_1  |   Applying paperless_mail.0002_auto_20201117_1334... OK
webserver_1  |   Applying paperless_mail.0003_auto_20201118_1940... OK
webserver_1  |   Applying paperless_mail.0004_mailrule_order... OK
webserver_1  |   Applying paperless_mail.0005_help_texts... OK
webserver_1  |   Applying paperless_mail.0006_auto_20210101_2340... OK
webserver_1  |   Applying paperless_mail.0007_auto_20210106_0138... OK
webserver_1  |   Applying paperless_mail.0008_auto_20210516_0940... OK
webserver_1  |   Applying paperless_mail.0009_mailrule_assign_tags... OK
webserver_1  |   Applying paperless_mail.0010_auto_20220311_1602... OK
webserver_1  |   Applying paperless_mail.0011_remove_mailrule_assign_tag... OK
webserver_1  |   Applying paperless_mail.0012_alter_mailrule_assign_tags... OK
webserver_1  |   Applying paperless_mail.0009_alter_mailrule_action_alter_mailrule_folder... OK
webserver_1  |   Applying paperless_mail.0013_merge_20220412_1051... OK
webserver_1  |   Applying paperless_mail.0014_alter_mailrule_action... OK
webserver_1  |   Applying paperless_mail.0015_alter_mailrule_action... OK
webserver_1  |   Applying sessions.0001_initial... OK
webserver_1  | Search index out of date. Updating...
webserver_1  | Executing /usr/local/bin/paperless_cmd.sh
webserver_1  | 2022-08-08 21:23:51,931 INFO Set uid to user 0 succeeded
webserver_1  | 2022-08-08 21:23:51,938 INFO supervisord started with pid 52
webserver_1  | 2022-08-08 21:23:52,943 INFO spawned: 'consumer' with pid 53
webserver_1  | 2022-08-08 21:23:52,949 INFO spawned: 'gunicorn' with pid 54
webserver_1  | 2022-08-08 21:23:52,955 INFO spawned: 'scheduler' with pid 55
webserver_1  | 2022-08-08 21:23:53,958 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
webserver_1  | 2022-08-08 21:23:53,958 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
webserver_1  | 2022-08-08 21:23:53,958 INFO success: scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
webserver_1  | [2022-08-08 21:23:54 +0000] [54] [INFO] Starting gunicorn 20.1.0
webserver_1  | [2022-08-08 21:23:54 +0000] [54] [INFO] Listening at: http://[::]:8000 (54)
webserver_1  | [2022-08-08 21:23:54 +0000] [54] [INFO] Using worker: paperless.workers.ConfigurableWorker
webserver_1  | [2022-08-08 21:23:54 +0000] [54] [INFO] Server is ready. Spawning workers
webserver_1  | [2022-08-08 21:23:57,004] [INFO] [paperless.management.consumer] Polling directory for changes: /usr/src/paperless/consume
webserver_1  | 21:23:57 [Q] INFO Q Cluster solar-south-artist-mockingbird starting.
webserver_1  | 21:23:57 [Q] INFO Process-1:1 ready for work at 78
webserver_1  | 21:23:57 [Q] INFO Process-1:2 monitoring at 79
webserver_1  | 21:23:57 [Q] INFO Process-1 guarding cluster solar-south-artist-mockingbird
webserver_1  | 21:23:57 [Q] INFO Process-1:3 pushing tasks at 80
webserver_1  | 21:23:57 [Q] INFO Q Cluster solar-south-artist-mockingbird running.
webserver_1  | 21:24:22 [Q] INFO Enqueued 1
webserver_1  | 21:24:22 [Q] INFO Process-1 created a task from schedule [Train the classifier]
webserver_1  | 21:24:22 [Q] INFO Process-1:1 processing [pizza-alabama-indigo-happy]
webserver_1  | 21:24:22 [Q] INFO Enqueued 1
webserver_1  | 21:24:22 [Q] INFO Process-1 created a task from schedule [Optimize the index]
webserver_1  | 21:24:22 [Q] INFO Enqueued 1
webserver_1  | 21:24:22 [Q] INFO Process-1 created a task from schedule [Perform sanity check]
webserver_1  | 21:24:22 [Q] INFO Enqueued 1
webserver_1  | 21:24:22 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
webserver_1  | 21:24:22 [Q] INFO Process-1:1 stopped doing work
webserver_1  | 21:24:23 [Q] INFO Processed [pizza-alabama-indigo-happy]
webserver_1  | 21:24:27 [Q] INFO recycled worker Process-1:1
webserver_1  | 21:24:27 [Q] INFO Process-1:4 ready for work at 103
webserver_1  | 21:24:27 [Q] INFO Process-1:4 processing [island-batman-potato-speaker]
webserver_1  | 21:24:28 [Q] INFO Process-1:4 stopped doing work
webserver_1  | 21:24:28 [Q] INFO Processed [island-batman-potato-speaker]
webserver_1  | 21:24:32 [Q] INFO recycled worker Process-1:4
webserver_1  | 21:24:32 [Q] INFO Process-1:5 ready for work at 106
webserver_1  | 21:24:32 [Q] INFO Process-1:5 processing [snake-autumn-spaghetti-oscar]
webserver_1  | [2022-08-08 21:24:33,014] [INFO] [paperless.sanity_checker] Sanity checker detected no issues.
webserver_1  | 21:24:33 [Q] INFO Process-1:5 stopped doing work
webserver_1  | 21:24:33 [Q] INFO Processed [snake-autumn-spaghetti-oscar]
webserver_1  | 21:24:37 [Q] INFO recycled worker Process-1:5
webserver_1  | 21:24:37 [Q] INFO Process-1:6 ready for work at 119
webserver_1  | 21:24:37 [Q] INFO Process-1:6 processing [green-diet-eleven-florida]
webserver_1  | 21:24:37 [Q] INFO Process-1:6 stopped doing work
webserver_1  | 21:24:37 [Q] INFO Processed [green-diet-eleven-florida]
webserver_1  | 21:24:42 [Q] INFO recycled worker Process-1:6
webserver_1  | 21:24:42 [Q] INFO Process-1:7 ready for work at 121
webserver_1  | 21:25:55 [Q] INFO Enqueued 1
webserver_1  | 21:25:55 [Q] INFO Process-1:7 processing [sample3.pdf]
webserver_1  | [2022-08-08 21:25:55,780] [INFO] [paperless.consumer] Consuming sample3.pdf
webserver_1  | 21:25:57 [Q] INFO Enqueued 1
webserver_1  | 21:26:00 [Q] INFO Enqueued 1
webserver_1  | 21:26:02 [Q] INFO Enqueued 1
webserver_1  | 21:26:04 [Q] INFO Enqueued 2
webserver_1  | [2022-08-08 21:26:14,473] [WARNING] [ocrmypdf._sync] Output file is okay but is not PDF/A (seems to be No PDF/A metadata in XMP)
webserver_1  | [2022-08-08 21:26:33,811] [INFO] [paperless.consumer] Document 2012-04-29 sample3 consumption finished
webserver_1  | 21:26:33 [Q] INFO Process-1:7 stopped doing work
webserver_1  | 21:26:33 [Q] INFO Processed [sample3.pdf]
webserver_1  | 21:26:37 [Q] INFO recycled worker Process-1:7
webserver_1  | 21:26:37 [Q] INFO Process-1:8 ready for work at 274
webserver_1  | 21:26:37 [Q] INFO Process-1:8 processing [2020-12-01.Uelzener.-.2022-05-22_13-26-25.pdf]
webserver_1  | [2022-08-08 21:26:38,427] [INFO] [paperless.consumer] Consuming 2020-12-01.Uelzener.-.2022-05-22_13-26-25.pdf
webserver_1  | [2022-08-08 21:26:43,424] [WARNING] [ocrmypdf._pipeline] Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
webserver_1  | [2022-08-08 21:27:14,192] [INFO] [paperless.consumer] Document 2020-12-02 2020-12-01.Uelzener.-.2022-05-22_13-26-25 consumption finished
webserver_1  | 21:27:14 [Q] INFO Process-1:8 stopped doing work
webserver_1  | 21:27:14 [Q] INFO Processed [2020-12-01.Uelzener.-.2022-05-22_13-26-25.pdf]
webserver_1  | 21:27:17 [Q] INFO recycled worker Process-1:8
webserver_1  | 21:27:17 [Q] INFO Process-1:9 ready for work at 324
webserver_1  | 21:27:17 [Q] INFO Process-1:9 processing [sample.pdf]
webserver_1  | [2022-08-08 21:27:18,506] [INFO] [paperless.consumer] Consuming sample.pdf
webserver_1  | [2022-08-08 21:27:28,729] [INFO] [paperless.consumer] Document 1999-02-20 sample consumption finished
webserver_1  | 21:27:28 [Q] INFO Process-1:9 stopped doing work
webserver_1  | 21:27:28 [Q] INFO Processed [sample.pdf]
webserver_1  | 21:27:32 [Q] INFO recycled worker Process-1:9
webserver_1  | 21:27:32 [Q] INFO Process-1:10 ready for work at 365
webserver_1  | 21:27:32 [Q] INFO Process-1:10 processing [sample.pdf_original]
webserver_1  | [2022-08-08 21:27:33,566] [INFO] [paperless.consumer] Consuming sample.pdf_original
webserver_1  | [2022-08-08 21:27:43,870] [INFO] [paperless.consumer] Document 1999-02-20 sample consumption finished
webserver_1  | 21:27:43 [Q] INFO Process-1:10 stopped doing work
webserver_1  | 21:27:43 [Q] INFO Processed [sample.pdf_original]
webserver_1  | 21:27:47 [Q] INFO recycled worker Process-1:10
webserver_1  | 21:27:47 [Q] INFO Process-1:11 ready for work at 415
webserver_1  | 21:27:47 [Q] INFO Process-1:11 processing [pdf-test.pdf]
webserver_1  | [2022-08-08 21:27:48,608] [INFO] [paperless.consumer] Consuming pdf-test.pdf
webserver_1  | [2022-08-08 21:27:48,727] [WARNING] [pdfminer.pdfpage] The PDF <_io.BufferedReader name='/tmp/paperless/paperless-upload-fs52xab8'> contains a metadata field indicating that it should not allow text extraction. Ignoring this field and proceeding. Use the check_extractable if you want to raise an error in this case
webserver_1  | [2022-08-08 21:27:49,827] [WARNING] [paperless.parsing.tesseract] This file is encrypted, OCR is impossible. Using any text present in the original file.
webserver_1  | [2022-08-08 21:28:02,561] [INFO] [paperless.consumer] Document 2022-08-08 pdf-test consumption finished
webserver_1  | 21:28:02 [Q] INFO Process-1:11 stopped doing work
webserver_1  | 21:28:02 [Q] INFO Processed [pdf-test.pdf]
webserver_1  | 21:28:02 [Q] INFO recycled worker Process-1:11
webserver_1  | 21:28:03 [Q] INFO Process-1:12 ready for work at 442
broker_1     | 1:M 08 Aug 2022 21:28:34.078 * 100 changes in 300 seconds. Saving...
broker_1     | 1:M 08 Aug 2022 21:28:34.079 * Background saving started by pid 22
broker_1     | 22:C 08 Aug 2022 21:28:34.093 * DB saved on disk
broker_1     | 22:C 08 Aug 2022 21:28:34.095 * RDB: 0 MB of memory used by copy-on-write
broker_1     | 1:M 08 Aug 2022 21:28:34.180 * Background saving terminated with success
</details>

**Comment by qcasey** [comment]
Although `np.show_config()` is also missing ASIMDFHM

```
>>> import numpy
numpy.show_config()>>> numpy.show_config()
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    found = 
    not found = ASIMDHP,ASIMDDP,ASIMDFHM
```

**Comment by stumpylog** [comment]
Is it not found in 1.7.1 as well?

**Comment by qcasey** [comment]
It appears to be the same as pedrom34's output

## 1.7.1

### numpy

```
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    found = 
    not found = ASIMDHP,ASIMDDP
```

### scipy

```
scipy.show_config()
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
```

**Comment by stumpylog** [comment]
Hm, maybe the number of tags/documents matters as well.

**Comment by pedrom34** [comment]
> Hm, maybe the number of tags/documents matters as well. This is very curious.

I have something like 900+ docs.

**Comment by pedrom34** [comment]
Hey!
I'm switching back to 1.7.1 because I don't really like the idea of this sword of Damocles waiting to crash my system 😬 
If you need more info or testing to solve this problem, I'm all ears 👂 and at your disposal!

**Comment by stumpylog** [comment]
No worries.  I've got a feeling we need a numpy release which includes this change: numpy/numpy/pull/21749

**Comment by pedrom34** [comment]
Good news! I'll test it as soon as it is available 👍

**Comment by Mannshoch** [comment]
Is my Problem here: https://github.com/paperless-ngx/paperless-ngx/discussions/1414 related to this here?

**Comment by stumpylog** [comment]
> Is my Problem here: #1414 related to this here?

No. That's likely something about your filesystem or database.

**Comment by stumpylog** [comment]
@pedrom34 If you can, can you test this against the new beta?  (With a backup!)  Numpy has been updated a couple times since, I'm hoping it works better.

If not, I'll probably just lock the version to an older one so people can upgrade and not run into this.

**Comment by pedrom34** [comment]
Hey!
So I made a backup for my 1.7.1 instance with 918 documents, moved to 1.9.0-beta.rc1 and relaunched the document classifier. About 3 minutes later the system is unreachable, I let it run nevertheless for about 1 hour, with no success...

Do you want me to test with rc2?

**Comment by qcasey** [comment]
Could you please post the server logs? They may not be relevant to this issue but might indicate a different problem.

**Comment by pedrom34** [comment]
You mean the paperless.log located in /data/log? Or something else?

**Comment by qcasey** [comment]
Yep - just curious if they look identical to what is in the original report?

> Latest lines before crash : 

```
[2022-08-05 16:04:27,710] [INFO] [paperless.migrations] Conversion to WebP completed, replaced 0000098.png with 0000098.webp
[2022-08-05 16:04:27,991] [INFO] [paperless.migrations] Conversion to WebP completed, replaced 0000606.png with 0000606.webp
[2022-08-05 16:04:28,020] [INFO] [paperless.migrations] Conversion completed in 108.198s
[2022-08-05 16:04:52,979] [INFO] [paperless.management.consumer] Polling directory for changes: /usr/src/paperless/consume
[2022-08-05 16:05:25,902] [INFO] [paperless.classifier] Classifier version updated, will re-train
[2022-08-05 16:05:26,009] [DEBUG] [paperless.classifier] Gathering data from database...
[2022-08-05 16:05:50,886] [DEBUG] [paperless.classifier] 913 documents, 27 tag(s), 59 correspondent(s), 29 document type(s). 0 storage path(es)
[2022-08-05 16:05:56,180] [DEBUG] [paperless.classifier] Vectorizing data...
[2022-08-05 16:06:18,812] [DEBUG] [paperless.classifier] Training tags classifier...
```

**Comment by pedrom34** [comment]
yep. From 9:35, it's 1.7.1 again:
```[2022-09-13 08:29:04,678] [INFO] [paperless.migrations] Conversion to WebP completed, replaced 0000335.png with 0000335.webp
[2022-09-13 08:29:04,725] [INFO] [paperless.migrations] Conversion completed in 120.939s
[2022-09-13 08:29:19,685] [INFO] [paperless.management.consumer] Polling directory for changes: /usr/src/paperless/consume
[2022-09-13 08:32:39,206] [INFO] [paperless.classifier] Classifier version updated, will re-train
[2022-09-13 08:32:39,268] [DEBUG] [paperless.classifier] Gathering data from database...
[2022-09-13 08:33:02,212] [DEBUG] [paperless.classifier] 918 documents, 27 tag(s), 59 correspondent(s), 29 document type(s). 0 storage path(es)
[2022-09-13 08:33:12,058] [DEBUG] [paperless.classifier] Vectorizing data...
[2022-09-13 08:33:31,439] [DEBUG] [paperless.classifier] Training tags classifier...

[2022-09-13 09:35:55,073] [INFO] [paperless.management.consumer] Polling directory for changes: /usr/src/paperless/src/../consume
[2022-09-13 09:36:29,757] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.
[2022-09-13 09:36:29,760] [DEBUG] [paperless.classifier] Gathering data from database...
[2022-09-13 09:36:55,788] [DEBUG] [paperless.classifier] 918 documents, 27 tag(s), 59 correspondent(s), 29 document type(s).
[2022-09-13 09:37:05,660] [DEBUG] [paperless.classifier] Vectorizing data...
[2022-09-13 09:37:26,721] [DEBUG] [paperless.classifier] Training tags classifier...
[2022-09-13 09:40:06,064] [DEBUG] [paperless.classifier] Training correspondent classifier...
[2022-09-13 09:41:44,628] [DEBUG] [paperless.classifier] Training document type classifier...
[2022-09-13 09:42:54,170] [INFO] [paperless.tasks] Saving updated classifier model to /usr/src/paperless/src/../data/classification_model.pickle...
[2022-09-13 09:51:03,682] [DEBUG] [paperless.classifier] Gathering data from database...
[2022-09-13 09:51:26,583] [DEBUG] [paperless.tasks] Training data unchanged.
[2022-09-13 10:50:33,171] [DEBUG] [paperless.classifier] Gathering data from database...

**Comment by stumpylog** [comment]
I don't see anything wrong with locking numpy to 1.22.3, which should resolve this for the moment.  And reporting it upstream as a probable capability detection issue.

**Comment by qcasey** [comment]
Thanks pedrom34. 

> I don't see anything wrong with locking numpy to 1.22.3,

Sounds good to me

**Comment by stumpylog** [comment]
@pedrom34 Thanks for helping us test this out.  The `:beta` image just built should fix this for you.  If you're able to test once again, that would be awesome.

**Comment by pedrom34** [comment]
Looks good to me. It's a bit heavier on resources than 1.7.1, but it works! 👍 
 ```root@46d217efd264:/usr/src/paperless/src# document_create_classifier
[2022-09-14 07:47:31,585] [INFO] [paperless.classifier] Classifier version updated, will re-train
[2022-09-14 07:55:55,880] [INFO] [paperless.tasks] Saving updated classifier model to /usr/src/paperless/data/classification_model.pickle...
root@46d217efd264:/usr/src/paperless/src# 
```

**Comment by shamoon** [comment]
Awesome thanks for confirming and stumpylog for the fix!

Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/17ae2aacbf58ec56d357fbc78c62f46ecc601165

**Comment by pedrom34** [comment]
Hello,

I just updated paperless-ngx to 1.10.0 and my issue is back 😭 
System becomes unreachable really quickly after paperless is running.
I understood in https://github.com/paperless-ngx/paperless-ngx/pull/1803 that I can lock numpy to 1.22.3, can you tell me how to do it? Or should I stay on paperless 1.9.2?

**Comment by stumpylog** [comment]
(Also, I'm sure numpy would like more information, if you have the time to help them out.  I created numpy/numpy/issues/22257 but could reproduce the slowdown on my Pi)

**Comment by pedrom34** [comment]
Thanks I'll try that tomorrow.
For the numpy issue, I'll message them there, but unless they'd guide me, I'm not sure I can help... It looks like it's waaaaay out of my geek league 😅

**Comment by stumpylog** [comment]
If you'll able to do some debugging, I have a simpler project I created to try and reproduce it.  I wasn't able to, but perhaps it's a ROCKPI thing.  Feel free to message me in our Matrix chat: https://matrix.to/#/#paperless:adnidor.de and I can explain more

**Comment by pedrom34** [comment]
OK, no problem, will do tomorrow. Thanks!

**Comment by raisindetre** [comment]
Just logging an initial note that this issue isn't yet resolved. Employed the numpy downgrade documented here and ran it using the environment config following for a couple of weeks but today it has reverted to old behaviour and is using 99% CPU and 93% of memory (of 2GB available on my NAS). Approx. 700 documents added in archive in the interim. Will confirm more details when I get control of the system back and am avail.

environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1000
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: [Zone]
      PAPERLESS_ADMIN_USER: [user]
      PAPERLESS_ADMIN_PASSWORD: [password]
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000/forms/libreoffice/convert#
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_OCR_MODE: skip_noarchive
      PAPERLESS_WEBSERVER_WORKERS: 1
      PAPERLESS_TASK_WORKERS: 1
      PAPERLESS_THREADS_PER_WORKER: 1
      PAPERLESS_CONSUMER_INOTIFY_DELAY: 4
